version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run: ls -al
  test1:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run: ls -al
  test2:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run: ls -al
  test3:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run: ls -al
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3

