version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "setup.py" }}

      - run:
          name: install python dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install scipy
            sudo pip install twine
            sudo python setup.py install
            python pergola/test/test_all.py

      - save_cache:
          key: dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"

  deploy:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install scipy
            sudo pip install twine
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = JoseEspinosa" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            sudo python setup.py sdist
            sudo python setup.py bdist_wheel
      - run:
          name: upload to testpypi
          command: |
            . venv/bin/activate
            twine upload --repository testpypi dist/*

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/